# Generated by Django 4.1.4 on 2022-12-26 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Productos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='image_url',
            field=models.CharField(max_length=1024),
        ),
    ]
